### ISSUE TITLE
Do you have an issue with lost packets with more that 260 kB/s?

### ISSUE THREAD

**Issue by frohro** [ExtremeElectronics/TeleCow#1]
Hi @ExtremeElectronics ,  I noted your Tele Cow project today.  It is very interesting work.  Thank you for sharing.  I am working on a project that also sends audio over the network with the Pico W.  https://github.com/frohro/SDR-TRX  I ran into an issue where  UDP packets got lost before being sent from the Pico W.  I was using the Ardunio-Pico framework.  If I got more than about 260 kB/s of data going out over UDP there would be lost packets.  My network was handling way more that 10x that bandwidth using a Linux box instead of the Pico W with no packet loss.  Both I and @earlephilhower, the author of the Arduino-Pico framework, are convinced the network is not the problem, but the loss is actually happening in the Pico W beyond the Arduino-Pico framework, perhaps in the Pico SDK or the WiFi blob or hardware.  https://github.com/earlephilhower/arduino-pico/discussions/2135  My present workaround is to send less data, but I would like to send more someday.  I believe RTP is built on top of UDP.  Have you experienced any similar thing in your tele cow project?

**Comment by ExtremeElectronics** [comment]
I've not really tried more than around 150 KB/s This project ~ 65kb/s  (This one pushes things a bit harder  https://github.com/ExtremeElectronics/PhiloFax )
Yes, I get dropped packets, but its UDP, what do you expect :) 
Also remember that the WiFi is sat on-top of an SPI interface. Plus, it's WiFi by default, that's mono-directional with cheap interfaces and prone to interference. 

One problem I have had is, if you work the cores too hard you miss data, I put this down to losing (SPI?) interrupts. 

With the PhiloFax, there is "A LOT GOING ON" so I put the packet drops down to me hammering the DMA's and interrupts and probably not giving time to the WiFi 

Maybe a deeper dive with the debug header is needed. Then again the LWIP has A LOT of settings and I'm not convinced the settings are best for all cases.
